service: mtglm-seasons

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'local'}
  region: us-east-1
  memorySize: 128
  environment:
    ALLOWED_ORIGIN: ${env:ALLOWED_ORIGIN}
    SEASON_TABLE_NAME: ${self:provider.stage}-mtglm-seasons
    PLAYER_TABLE_NAME:
      Fn::ImportValue: ${self:provider.stage}-mtglm-PlayerTableName
    USER_POOL_ID:
      Fn::ImportValue: ${self:provider.stage}-mtglm-UserPoolId

package:
  include:
    - ../build/**
    - ../node_modules/**

plugins:
  - serverless-offline
  - serverless-iam-roles-per-function
  - serverless-aws-documentation

resources:
  Resources:
    SeasonsApiGatewayAuthorizer: ${file(partials/apiGatewayAuthorizer.yml)}
    SeasonsTable: ${file(partials/dynamodb/seasons.yml)}
  Outputs:
    seasonTableArn: ${file(partials/outputs/TableArn.yml)}
    seasonTableName: ${file(partials/outputs/TableName.yml)}

custom:
  documentation: ${file(partials/documentation.yml)}
  userPoolArn:
    Fn::ImportValue: ${self:provider.stage}-mtglm-UserPoolArn
  userPoolName:
    Fn::ImportValue: ${self:provider.stage}-mtglm-UserPoolName

functions:
  Get: ${file(partials/functions/get.yml)}
  GetAllDetails: ${file(partials/functions/getAllDetails.yml)}
  Create: ${file(partials/functions/create.yml)}
  Delete: ${file(partials/functions/delete.yml)}
  Update: ${file(partials/functions/update.yml)}
